# Removed deprecated version field as per Docker Compose v2 standards
services:
  db:
    image: postgres:16
    container_name: flowvision_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowvision
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - flowvision_network

  redis:
    image: redis:7-alpine
    container_name: flowvision_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - flowvision_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: flowvision_redis_ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - flowvision_network
    profiles:
      - dev # Only start in dev profile

volumes:
  db_data:
  redis_data:

networks:
  flowvision_network:
    driver: bridge
